export enum StatusCodeEnums {
  OK = "OK",
  UNEXPECTED = "UNEXPECTED",
  NEWS_EXISTS = "NEWS_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
  INVALID_TOKEN = "INVALID_TOKEN",
  UNAUTHORIZED = "UNAUTHORIZED",
}
